# Security Configuration for Secret Scanning

# This file configures GitHub's secret scanning feature
# https://docs.github.com/en/code-security/secret-scanning

# Custom patterns for detecting secrets specific to MyCrypto

# Private keys and mnemonic phrases
private_keys:
  - pattern: "-----BEGIN (RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----"
    description: "Private key detected"
    
# API Keys
api_keys:
  - pattern: "(?i)(api[_-]?key|apikey)[\\s]*[:=][\\s]*['\"]?[a-zA-Z0-9]{20,}['\"]?"
    description: "API key detected"
    
# Ethereum private keys (64 hex characters)
ethereum_keys:
  - pattern: "0x[a-fA-F0-9]{64}"
    description: "Potential Ethereum private key"
    
# Mnemonic seed phrases (12-24 words)
mnemonic:
  - pattern: "(?i)(mnemonic|seed phrase|recovery phrase)\\s*[:=]\\s*['\"]?([a-z]+\\s+){11,23}[a-z]+['\"]?"
    description: "Mnemonic seed phrase detected"

# Access tokens
tokens:
  - pattern: "(?i)(access[_-]?token|accesstoken)[\\s]*[:=][\\s]*['\"]?[a-zA-Z0-9]{20,}['\"]?"
    description: "Access token detected"
  - pattern: "(?i)(bearer[\\s]+)[a-zA-Z0-9\\-_\\.]+\\.[a-zA-Z0-9\\-_\\.]+\\.[a-zA-Z0-9\\-_\\.]+"
    description: "JWT token detected"

# Database credentials
database:
  - pattern: "(?i)(mysql|postgres|mongodb):\\/\\/[^\\s:]+:[^\\s@]+@[^\\s]+"
    description: "Database connection string with credentials"

# AWS credentials
aws:
  - pattern: "(?i)(aws[_-]?access[_-]?key[_-]?id|aws[_-]?secret[_-]?access[_-]?key)[\\s]*[:=][\\s]*['\"]?[A-Z0-9]{20}['\"]?"
    description: "AWS credentials detected"

# Note: GitHub's built-in secret scanning already detects many common patterns.
# These custom patterns are specific to cryptocurrency and MyCrypto use cases.
